#############################################################################
# Makefile for building: library
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? 6? 18 17:54:58 2012
# Project:  library.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile library.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Author.cpp \
		book.cpp \
		main.cpp \
		mainwindow.cpp \
		manager.cpp \
		managerwindow.cpp \
		register.cpp \
		searchwindow.cpp \
		user.cpp \
		userinfor.cpp \
		userwindow.cpp moc_mainwindow.cpp \
		moc_managerwindow.cpp \
		moc_register.cpp \
		moc_searchwindow.cpp \
		moc_userinfor.cpp \
		moc_userwindow.cpp \
		qrc_resourse.cpp
OBJECTS       = Author.o \
		book.o \
		main.o \
		mainwindow.o \
		manager.o \
		managerwindow.o \
		register.o \
		searchwindow.o \
		user.o \
		userinfor.o \
		userwindow.o \
		moc_mainwindow.o \
		moc_managerwindow.o \
		moc_register.o \
		moc_searchwindow.o \
		moc_userinfor.o \
		moc_userwindow.o \
		qrc_resourse.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		library.pro
QMAKE_TARGET  = library
DESTDIR       = 
TARGET        = library

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: library.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile library.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile library.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/library1.0.0 || $(MKDIR) .tmp/library1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/library1.0.0/ && $(COPY_FILE) --parents Author.h book.h mainwindow.h manager.h managerwindow.h redblacktree.h register.h searchwindow.h user.h userinfor.h userwindow.h .tmp/library1.0.0/ && $(COPY_FILE) --parents resourse.qrc .tmp/library1.0.0/ && $(COPY_FILE) --parents Author.cpp book.cpp main.cpp mainwindow.cpp manager.cpp managerwindow.cpp register.cpp searchwindow.cpp user.cpp userinfor.cpp userwindow.cpp .tmp/library1.0.0/ && (cd `dirname .tmp/library1.0.0` && $(TAR) library1.0.0.tar library1.0.0 && $(COMPRESS) library1.0.0.tar) && $(MOVE) `dirname .tmp/library1.0.0`/library1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/library1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_managerwindow.cpp moc_register.cpp moc_searchwindow.cpp moc_userinfor.cpp moc_userwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_managerwindow.cpp moc_register.cpp moc_searchwindow.cpp moc_userinfor.cpp moc_userwindow.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_managerwindow.cpp: managerwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) managerwindow.h -o moc_managerwindow.cpp

moc_register.cpp: register.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) register.h -o moc_register.cpp

moc_searchwindow.cpp: searchwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) searchwindow.h -o moc_searchwindow.cpp

moc_userinfor.cpp: userinfor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) userinfor.h -o moc_userinfor.cpp

moc_userwindow.cpp: userwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) userwindow.h -o moc_userwindow.cpp

compiler_rcc_make_all: qrc_resourse.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resourse.cpp
qrc_resourse.cpp: resourse.qrc \
		book.txt \
		user.txt \
		imgs/1.png \
		imgs/2.png \
		imgs/1.jpg \
		imgs/open.png
	/usr/bin/rcc -name resourse resourse.qrc -o qrc_resourse.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

Author.o: Author.cpp book.h \
		Author.h \
		manager.h \
		redblacktree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Author.o Author.cpp

book.o: book.cpp book.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o book.o book.cpp

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		userinfor.h \
		register.h \
		manager.h \
		redblacktree.h \
		user.h \
		userwindow.h \
		managerwindow.h \
		searchwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

manager.o: manager.cpp manager.h \
		redblacktree.h \
		Author.h \
		user.h \
		book.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o manager.o manager.cpp

managerwindow.o: managerwindow.cpp managerwindow.h \
		user.h \
		manager.h \
		redblacktree.h \
		searchwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o managerwindow.o managerwindow.cpp

register.o: register.cpp register.h \
		user.h \
		manager.h \
		redblacktree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o register.o register.cpp

searchwindow.o: searchwindow.cpp searchwindow.h \
		manager.h \
		redblacktree.h \
		user.h \
		Author.h \
		book.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o searchwindow.o searchwindow.cpp

user.o: user.cpp book.h \
		user.h \
		manager.h \
		redblacktree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user.o user.cpp

userinfor.o: userinfor.cpp userinfor.h \
		user.h \
		manager.h \
		redblacktree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userinfor.o userinfor.cpp

userwindow.o: userwindow.cpp userwindow.h \
		user.h \
		manager.h \
		redblacktree.h \
		book.h \
		userinfor.h \
		searchwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userwindow.o userwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_managerwindow.o: moc_managerwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_managerwindow.o moc_managerwindow.cpp

moc_register.o: moc_register.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_register.o moc_register.cpp

moc_searchwindow.o: moc_searchwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_searchwindow.o moc_searchwindow.cpp

moc_userinfor.o: moc_userinfor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_userinfor.o moc_userinfor.cpp

moc_userwindow.o: moc_userwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_userwindow.o moc_userwindow.cpp

qrc_resourse.o: qrc_resourse.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resourse.o qrc_resourse.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

